// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/oleg-koval/veto/pkg/router"
)

// ExecutorMock is a mock implementation of router.Executor.
type ExecutorMock struct {
	RunFunc func(ctx context.Context, prompt string) router.AdmissionResult

	calls struct {
		Run []struct {
			Ctx    context.Context
			Prompt string
		}
	}
	lockRun sync.RWMutex
}

func (mock *ExecutorMock) Run(ctx context.Context, prompt string) router.AdmissionResult {
	if mock.RunFunc == nil {
		panic("ExecutorMock.RunFunc: method is nil but Executor.Run was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Prompt string
	}{Ctx: ctx, Prompt: prompt}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	return mock.RunFunc(ctx, prompt)
}

func (mock *ExecutorMock) RunCalls() []struct {
	Ctx    context.Context
	Prompt string
} {
	mock.lockRun.RLock()
	defer mock.lockRun.RUnlock()
	return append([]struct {
		Ctx    context.Context
		Prompt string
	}{}, mock.calls.Run...)
}
